redis:
  host: 127.0.0.1
  port: 6379

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: '123456'

replication:
  server_id: 1
  master_log_file: binlog.000172
  master_log_position: 2252220

server:
  host: 0.0.0.0
  port: 8000
  debug: true
