version: "3"
services:
  producer:
    network_mode: host
    image: fettler
    command: fettler produce
    depends_on:
      - server
  consumer:
    network_mode: host
    image: fettler
    command: fettler consume
    depends_on:
      - server
  server:
    build: .
    image: fettler
    network_mode: host
    command: fettler serve
