name: ci
on: [ push, pull_request ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: '123456'
          mysql database: 'test'
      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.1.0
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: false
      - name: Install deps
        run: make deps
      - name: Run server
        run: nohup fettler serve &
      - name: Run producer
        run: nohup fettler produce &
      - name: Run consumer
        run: nohup fettler consume &
      - name: Run CI
        run: make ci
